# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2510b9b60945ed8c08a5adcf37a316cb43c731aa0d8eb1f872c72998228cbbcc2befb1a7db0f16c5598962f8b6ff0deb7a50882ac2d39ec396d69140fe34c2f6

test:
  secret_key_base: 958dd205a826ed866f3329722e53456c458627a5d702f7c1eb650218e3657cb47c3e81224ab8e03b2a4fabf29127aed023163c019f20143c20e6b0cdf3c00b33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
